server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 888888
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848  # nacos 服务地址
      discovery:
        cluster-name: SH
#        ephemeral: false  # false -> 非临时实例
#        namespace: d8af3be8-03f7-4c3d-aac4-054f653a389d  # namespace配置 dev环境
#        group: order   # namespace 配置：指定分组 group
    # sentinel配置文件
    sentinel:
      transport:
        dashboard: localhost:8090 # sentinel 控制台地址
      web-context-unify: false # Sentinel 会默认将Controller做context整合，导致链路失效！！！

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

# 配置负载均衡规则：指定某一个服务 userservice
userservice:
  ribbon:
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule  # 轮询规则
    # 负载均衡规则：优先选择本地集群，在本地集群中的多个服务采用随机策略
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients:
      - userservice #指定饥饿加载的服务名



##  eureka 注册中心 配置
#eureka:
#  client:
#    service-url: # eureka 的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka


# feign 日志(自定义)
feign:
  client:
    config:
      default:  # 如果针对某个微服务的配置
        logger-level: FULL  # NONE、BASIC、HEADERS、FULL
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数
  # 开启sentinel功能
  sentinel:
    enabled: true # 开启feign对sentinel的支持
