server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848  # nacos 地址
    gateway:
      routes:
        - id: user-service  # 路由标识，必须唯一
          uri: lb://userservice  # 路由目标地址
          predicates: # 路由断言，判断路由是否符合规则
            - Path=/user/**  # 路径断言，判断路径是否是以/user开头，如果是，则符合规则。
          # 局部过滤器
          filters:
            - AddRequestHeader=Truth,Harmony is freaking awesome!  #添加请求头

        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
            - Before=2031-01-20T17:42:47.789-07:00[America/Denver]
      default-filters:  # 默认过滤器 对所有的路由都生效
        - AddRequestHeader=Truth,huawei is perfect!!!
        - AddRequestHeader=origin,gateway

#      # 全局的跨域处理
#      globalcors:
#        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: # 允许哪些网站的跨域请求
#              - "http://localhost:8090"
#            allowedMethods: # 允许的跨域ajax的请求方式
#              - "GET"
#              - "POST"
#              - "DELETE"
#              - "PUT"
#              - "OPTIONS"
#            allowedHeaders: "*" # 允许在请求中携带的头信息
#            allowCredentials: true # 是否允许携带cookie
#            maxAge: 360000 # 这次跨域检测的有效期